databases:
  - name: mysite
    databaseName: mysite
    user: mysite
    plan: free

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    # Comandos de construcción podrían estar aquí en lugar de usar render-build.sh
    # buildCommand: "bundle install && bundle exec rake assets:precompile && bundle exec rake assets:clean"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString

