services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: "bundle install && bundle exec rake assets:precompile && bundle exec rake assets:clean"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
